services:
  fix-permissions:
    image: alpine:latest
    entrypoint:
      - /bin/sh
      - -ec
    command:
      - |
        chown -R 65532:65532 /certs
        chown -R 65532:65532 /config
    volumes:
      - certs:/certs
      - ./private/config:/config

  certgen:
    image: envoyproxy/gateway:v1.2.3
    depends_on:
      fix-permissions:
        condition: service_completed_successfully
    command:
      - certgen
      - --local
    volumes:
      - certs:/tmp/envoy-gateway/certs
      - ./private/config:/config

  envoy-gateway:
    image: envoyproxy/gateway:v1.2.3
    depends_on:
      certgen:
        condition: service_completed_successfully
    command:
      - server
      - --config-path
      - /standalone.yaml
    volumes:
      - certs:/tmp/envoy-gateway/certs
      - ./private/config:/config
      - ./private/standalone.yaml:/standalone.yaml:ro

    # ports:
    #   - 8080:8080
    #   - 8443:8443
    #   - 9901:9901
    # network_mode: host
    # environment:
    #   ENVOY_UID: "0"
    #   ENVOY_GID: "0"
  #   healthcheck:
  #     test:
  #       - CMD-SHELL
  #       - curl --silent --fail http://localhost:8080 || exit 1
  #     interval: 10s
  #     retries: 10
  #     start_period: 10s
  #     timeout: 5s

  # controller:
  #   image: compose-gateway
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./controller:/controller:ro
  #     - ./private/config:/config

volumes:
  certs:
    driver: local
  config:
    driver: local
