services:
  certgen:
    image: envoyproxy/gateway:v1.3.2
    entrypoint:
      - envoy-gateway
    command:
      - certgen
      - --local
    volumes:
      - certs:/tmp

  envoy-gateway:
    image: envoyproxy/gateway:v1.3.2
    depends_on:
      certgen:
        condition: service_completed_successfully
      controller:
        condition: service_started
    network_mode: host
    user: root
    entrypoint:
      - envoy-gateway
    command:
      - server
      - --config-path
      - /config/config.yaml
    volumes:
      - certs:/tmp
      - config:/config

  controller:
    image: ghcr.io/dshatokhin/compose-gateway:latest
    environment:
      COMPOSE_GATEWAY_PORTS: "80"
      # COMPOSE_GATEWAY_SECURE_PORTS: "443"
      # COMPOSE_GATEWAY_TLS_CRT_FILE: "/certs/cert.pem"
      # COMPOSE_GATEWAY_TLS_KEY_FILE: "/certs/key.pem"
      # COMPOSE_ENVOY_GATEWAY_LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/tmp
      - config:/config

volumes:
  certs:
    driver: local
  config:
    driver: local
