services:
  # https://theorangeone.net/posts/expose-docker-internal-dns/
  # coredns:
  #   image: coredns/coredns:1.12.0
  #   volumes:
  #     - ./Corefile:/home/nonroot/Corefile:ro
  #   ports:
  #     - 5533:53/udp

  envoy:
    image: envoyproxy/envoy:v1.32-latest
    network_mode: host
    environment:
      ENVOY_UID: "0"
      ENVOY_GID: "0"
    depends_on:
      controller:
        condition: service_started
    # healthcheck:
    #   test:
    #     - CMD-SHELL
    #     - curl --silent --fail http://localhost:8080 || exit 1
    #   interval: 10s
    #   retries: 10
    #   start_period: 10s
    #   timeout: 5s
    command:
    - envoy
    - -c
    - /bootstrap.yaml
    volumes:
      - ./controller/bootstrap.yaml:/bootstrap.yaml
      - ./private/config:/config
    # ports:
    #   - 8080:8080
    #   - 8443:8443
    #   - 9901:9901

  controller:
    image: compose-gateway
    # network_mode: host
    # dns:
    #   - 127.0.0.1
    # healthcheck:
    #   test:
    #     - CMD-SHELL
    #     - '[[ -f /var/run/controller ]] || exit 1'
    #   interval: 5s
    #   retries: 10
    #   start_period: 5s
    #   timeout: 1s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./controller:/controller:ro
      - ./private/config:/config

# networks:
#   net:
#     driver: host

volumes:
  config:
    driver: local
