version: '3'

vars:
  IMAGE_TAG: ghcr.io/dshatokhin/compose-gateway:latest

tasks:
  build:
    desc: Builds the container image for compose-gateway
    cmds:
    - docker build -t {{.IMAGE_TAG}} .

  publish:
    desc: Pushes the container image to the Github Registry
    cmds:
    - docker push {{.IMAGE_TAG}}

  render:
    env:
      COMPOSE_GATEWAY_PORTS: "80"
    vars:
      PAYLOAD:
        sh: cat private/payload.json
    cmds:
    - pkl eval controller/main.pkl -p payload='{{.PAYLOAD}}'
    # - pkl eval controller/main.pkl -p container='{{.CONTAINER}}' -p type='{{.TYPE}}' -p action='{{.ACTION}}' -p configFile='{{.CONFIG_FILE}}' -p annotations='{{.ANNOTATIONS}}' -p ipAddresses='{{.IP_ADDRESSES}}'
